In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r'/home/shuvo/Documents/NLP/Bag Of Words (BOW)/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=0.2)

In [9]:
X_train.shape

(4457,)

In [10]:
X_test

5474    Where's mummy's boy ? Is he being good or bad ...
1044    Mmm thats better now i got a roast down me! i’...
268     Ur ringtone service has changed! 25 Free credi...
4438                        How come u got nothing to do?
631                   Please dont say like that. Hi hi hi
                              ...                        
694     Will purchase d stuff today and mail to you. D...
5179    Hi hope u r both ok, he said he would text and...
200              Found it, ENC  &lt;#&gt; , where you at?
4731    I dont know ask to my brother. Nothing problem...
1943       K...k:)why cant you come here and search job:)
Name: Message, Length: 1115, dtype: object

In [11]:
type(X_train)

pandas.core.series.Series

In [12]:
X_train[:4]

5163                              Ok leave no need to ask
2452    I know complain num only..bettr directly go to...
1497    I'm always on yahoo messenger now. Just send t...
1138                             LOL ... No just was busy
Name: Message, dtype: object

In [13]:
type(y_train)

pandas.core.series.Series

In [14]:
y_train[0:4]

5163    0
2452    0
1497    0
1138    0
Name: spam, dtype: int64

In [19]:
type(X_train.values)

numpy.ndarray

In [20]:
'''The CountVectorizer from sklearn.feature_extraction.text is used for converting a collection 
of text documents into a matrix of token counts. It's a key step in the "Bag of Words" (BoW) model 
for text preprocessing in natural language processing (NLP).'''

from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58843 stored elements and shape (4457, 7686)>

In [23]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [24]:
X_train_cv.shape

(4457, 7686)

In [42]:
v.get_feature_names_out()[1103]

'ask'

In [30]:
v.vocabulary_

{'ok': 4879,
 'leave': 4025,
 'no': 4759,
 'need': 4691,
 'to': 6890,
 'ask': 1103,
 'know': 3927,
 'complain': 1932,
 'num': 4817,
 'only': 4908,
 'bettr': 1337,
 'directly': 2329,
 'go': 3140,
 'bsnl': 1537,
 'offc': 4857,
 'nd': 4677,
 'apply': 1037,
 'for': 2917,
 'it': 3726,
 'always': 942,
 'on': 4897,
 'yahoo': 7607,
 'messenger': 4423,
 'now': 4806,
 'just': 3842,
 'send': 5974,
 'the': 6770,
 'message': 4418,
 'me': 4367,
 'and': 971,
 'll': 4124,
 'get': 3098,
 'you': 7647,
 'may': 4359,
 'have': 3329,
 'in': 3616,
 'mobile': 4507,
 'mode': 4518,
 'sha': 6014,
 'but': 1578,
 'will': 7464,
 'reply': 5677,
 'lol': 4147,
 'was': 7337,
 'busy': 1577,
 'gr8': 3186,
 'poly': 5255,
 'tones': 6916,
 'all': 919,
 'mobs': 4513,
 'direct': 2328,
 '2u': 418,
 'rply': 5794,
 'with': 7490,
 'title': 6871,
 '8007': 646,
 'eg': 2533,
 'breathe1': 1500,
 'titles': 6872,
 'crazyin': 2069,
 'sleepingwith': 6180,
 'finest': 2839,
 'ymca': 7641,
 'getzed': 3106,
 'co': 1873,
 'uk': 7067,
 'pobox3

In [43]:
X_train_np = X_train_cv.toarray()
X_train_np[:4][0]#first email

array([0, 0, 0, ..., 0, 0, 0])

In [44]:
np.where(X_train_np[0]!=0)

(array([1103, 4025, 4691, 4759, 4879, 6890]),)

In [45]:
X_train[:4]

5163                              Ok leave no need to ask
2452    I know complain num only..bettr directly go to...
1497    I'm always on yahoo messenger now. Just send t...
1138                             LOL ... No just was busy
Name: Message, dtype: object

In [46]:
X_train_np[0][1103]

np.int64(1)

In [48]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [49]:
X_test_cv = v.transform(X_test)

In [52]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       979
           1       0.95      0.96      0.95       136

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [54]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

# Train the model using sklearn pipeline and reduce number of lines of code

In [55]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [56]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [57]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       979
           1       0.95      0.96      0.95       136

    accuracy                           0.99      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

